package helper

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fprl/simple-vps/internal/caddy"
	"github.com/fprl/simple-vps/internal/config"
	"github.com/fprl/simple-vps/internal/identity"
)

func caddyfilePath(app, env string) string {
	return identity.CaddyFragmentFile(app, env)
}

func renderAppCaddyfile(app, env string, ctx *config.AppContext, release string) (string, error) {
	return renderAppCaddyfileWithProcessNames(app, env, ctx, release, nil)
}

func renderAppCaddyfileWithProcessNames(app, env string, ctx *config.AppContext, release string, processNames map[string]string) (string, error) {
	type hostKey struct {
		host string
		tls  string
	}
	grouped := map[hostKey][]string{}
	for _, name := range sortedKeys(ctx.Routes) {
		route := ctx.Routes[name]
		key := hostKey{host: route.Host, tls: normalizeTLS(route.TLS)}
		grouped[key] = append(grouped[key], name)
	}

	keys := make([]hostKey, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].host != keys[j].host {
			return keys[i].host < keys[j].host
		}
		return keys[i].tls < keys[j].tls
	})

	var blocks []string
	for _, key := range keys {
		routeNames := grouped[key]
		sort.SliceStable(routeNames, func(i, j int) bool {
			left := ctx.Routes[routeNames[i]].Path
			right := ctx.Routes[routeNames[j]].Path
			if left == right {
				return routeNames[i] < routeNames[j]
			}
			if left == "" {
				return false
			}
			if right == "" {
				return true
			}
			return len(left) > len(right)
		})

		var prelude string
		if key.tls == "internal" {
			prelude = "\ttls internal\n"
		}
		var body strings.Builder
		useHandles := len(routeNames) > 1 || ctx.Routes[routeNames[0]].Path != ""
		for _, routeName := range routeNames {
			rendered, err := renderRouteBody(app, env, ctx, routeName, release, processNames, useHandles)
			if err != nil {
				return "", err
			}
			body.WriteString(rendered)
		}
		quotedHost, err := caddy.CaddyQuote(key.host)
		if err != nil {
			return "", err
		}
		blocks = append(blocks, fmt.Sprintf("%s {\n%s%s}\n", quotedHost, prelude, body.String()))
	}
	return "# generated by simple-vps server app apply — do not edit\n" + strings.Join(blocks, "\n"), nil
}

func renderRouteBody(app, env string, ctx *config.AppContext, routeName string, release string, processNames map[string]string, wrap bool) (string, error) {
	route := ctx.Routes[routeName]
	body, err := renderRouteDirectives(app, env, ctx, routeName, release, processNames)
	if err != nil {
		return "", err
	}
	if !wrap {
		return indent(body, 1), nil
	}
	if route.Path == "" {
		return "\thandle {\n" + indent(body, 2) + "\t}\n", nil
	}
	if route.Serve != "" {
		return fmt.Sprintf("\thandle %s {\n\t\trewrite * /\n%s\t}\n\thandle_path %s/* {\n%s\t}\n",
			route.Path, indent(body, 2), route.Path, indent(body, 2)), nil
	}
	return fmt.Sprintf("\thandle %s {\n%s\t}\n\thandle %s/* {\n%s\t}\n",
		route.Path, indent(body, 2), route.Path, indent(body, 2)), nil
}

func renderRouteDirectives(app, env string, ctx *config.AppContext, routeName string, release string, processNames map[string]string) (string, error) {
	route := ctx.Routes[routeName]
	switch {
	case route.Process != "":
		proc, ok := ctx.Processes[route.Process]
		if !ok || proc.Port == nil {
			return "", fmt.Errorf("route %q references process %q with no port", routeName, route.Process)
		}
		upstream := identity.ContainerName(app, env, route.Process, release)
		if processNames != nil && processNames[route.Process] != "" {
			upstream = processNames[route.Process]
		}
		return fmt.Sprintf("reverse_proxy http://%s:%d\n", upstream, *proc.Port), nil
	case route.Serve != "":
		root := filepath.Join(identity.StaticDir(app, env), "releases", release, routeName)
		quotedRoot, err := caddy.CaddyQuote(root)
		if err != nil {
			return "", fmt.Errorf("route %q: %v", routeName, err)
		}
		return fmt.Sprintf("root * %s\nfile_server\n", quotedRoot), nil
	case route.Redirect != "":
		quotedTo, err := caddy.CaddyQuote(route.Redirect)
		if err != nil {
			return "", fmt.Errorf("route %q: %v", routeName, err)
		}
		return fmt.Sprintf("redir %s permanent\n", quotedTo), nil
	default:
		return "", fmt.Errorf("route %q has no target", routeName)
	}
}

func normalizeTLS(tls string) string {
	if tls == "" {
		return "auto"
	}
	return tls
}

func indent(s string, levels int) string {
	prefix := strings.Repeat("\t", levels)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line == "" {
			continue
		}
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}

func writeAppCaddyfile(app, env string, ctx *config.AppContext, release string) error {
	return writeAppCaddyfileWithProcessNames(app, env, ctx, release, nil)
}

func writeAppCaddyfileWithProcessNames(app, env string, ctx *config.AppContext, release string, processNames map[string]string) error {
	content, err := renderAppCaddyfileWithProcessNames(app, env, ctx, release, processNames)
	if err != nil {
		return err
	}
	path := caddyfilePath(app, env)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}

// snapshotCaddyFragment reads the existing fragment so a failed deploy
// can restore it. Returns (contents, true, nil) when a fragment exists,
// (nil, false, nil) when nothing is there, or an error for anything
// other than ENOENT.
func snapshotCaddyFragment(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if err == nil {
		return data, true, nil
	}
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	return nil, false, err
}

// restoreCaddyFragment puts back what snapshotCaddyFragment captured.
// If there was no previous fragment, remove the new one so subsequent
// reloads don't trip on it.
func restoreCaddyFragment(path string, prev []byte, existed bool) error {
	if existed {
		return os.WriteFile(path, prev, 0644)
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
