package caddy

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fprl/simple-vps/internal/store"
	"github.com/fprl/simple-vps/internal/utils"
)

const (
	GeneratedMarker = "# Generated by Simple VPS. Do not edit by hand."
	HashPrefix      = "# simple-vps-sha256: "
)

func CaddyfilePath() string {
	if p := os.Getenv("SIMPLE_VPS_CADDYFILE_PATH"); p != "" {
		return p
	}
	return "/etc/caddy/Caddyfile"
}

func ManagedCaddyDir() string {
	if p := os.Getenv("SIMPLE_VPS_MANAGED_CADDY_DIR"); p != "" {
		return p
	}
	return "/etc/caddy/simple-vps"
}

func RoutesCaddyfilePath() string {
	return filepath.Join(ManagedCaddyDir(), "routes.caddy")
}

func UserCaddyDir() string {
	if p := os.Getenv("SIMPLE_VPS_USER_CADDY_DIR"); p != "" {
		return p
	}
	return "/etc/caddy/conf.d"
}

func CaddyQuote(value string) (string, error) {
	if strings.ContainsAny(value, "\r\n") {
		return "", errors.New("Caddyfile values cannot contain newlines")
	}
	b, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func ManagedContent(body string) string {
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	hasher := sha256.New()
	hasher.Write([]byte(body))
	digest := hex.EncodeToString(hasher.Sum(nil))
	return fmt.Sprintf("%s\n%s%s\n%s", GeneratedMarker, HashPrefix, digest, body)
}

func ManagedHashIsValid(content string) bool {
	lines := strings.Split(content, "\n")
	// If the file ends with a trailing newline, split leaves an empty string at the end.
	// We reconstruct correctly.
	if len(lines) < 3 {
		return false
	}
	if strings.TrimRight(lines[0], "\r") != GeneratedMarker {
		return false
	}
	hashLine := strings.TrimSpace(lines[1])
	if !strings.HasPrefix(hashLine, HashPrefix) {
		return false
	}
	expected := hashLine[len(HashPrefix):]

	// Reconstruct body (from line index 2 onwards)
	body := strings.Join(lines[2:], "\n")
	hasher := sha256.New()
	hasher.Write([]byte(body))
	actual := hex.EncodeToString(hasher.Sum(nil))
	return actual == expected
}

func IsOldSimpleVpsGenerated(content string) bool {
	lines := strings.Split(content, "\n")
	if len(lines) < 2 {
		return false
	}
	return strings.TrimRight(lines[0], "\r") == GeneratedMarker && strings.HasPrefix(lines[1], "# Source:")
}

func IsDefaultCaddyfile(content string) bool {
	return strings.Contains(content, "root * /usr/share/caddy") && strings.Contains(content, "file_server")
}

func EnsureCanReplaceManagedFile(path string, force bool, allowDefault bool) error {
	if force {
		return nil
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	content := string(data)
	if ManagedHashIsValid(content) || IsOldSimpleVpsGenerated(content) {
		return nil
	}
	if allowDefault && IsDefaultCaddyfile(content) {
		return nil
	}
	return fmt.Errorf("manual edits detected in %s; move custom Caddy config to %s or rerun with --force", path, UserCaddyDir())
}

func RenderCaddyfile() string {
	statePath := store.Default().RoutesPath()
	body := fmt.Sprintf("# Source: %s\n\nimport simple-vps/*.caddy\nimport conf.d/*.caddy\n\n", statePath)
	return ManagedContent(body)
}

func RenderRoutesCaddyfile(s *store.RoutesFile) (string, error) {
	statePath := store.Default().RoutesPath()
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Source: %s\n\nhttp://:8080 {\n\tbind 127.0.0.1\n", statePath))

	for i, r := range s.Routes {
		lines, err := renderRoute(r, i)
		if err != nil {
			return "", err
		}
		for _, line := range lines {
			sb.WriteString(line)
			sb.WriteByte('\n')
		}
	}

	sb.WriteString("\trespond \"Simple VPS Caddy ready\" 404\n}\n\n")
	return ManagedContent(sb.String()), nil
}

func renderHeaders(headers map[string]string) ([]string, error) {
	var lines []string
	// Sort header names for deterministic output
	var keys []string
	for k := range headers {
		keys = append(keys, k)
	}
	sortStringsCaseInsensitive(keys)

	for _, k := range keys {
		v := headers[k]
		quotedVal, err := CaddyQuote(v)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fmt.Sprintf("\t\theader %s %s", k, quotedVal))
	}
	return lines, nil
}

func sortStringsCaseInsensitive(slice []string) {
	sort.Slice(slice, func(i, j int) bool {
		return strings.ToLower(slice[i]) < strings.ToLower(slice[j])
	})
}

func renderRoute(r store.Route, index int) ([]string, error) {
	matcher := fmt.Sprintf("route_%d", index)
	lines := []string{
		fmt.Sprintf("\t@%s host %s", matcher, r.Host),
		fmt.Sprintf("\thandle @%s {", matcher),
	}

	switch r.Type {
	case "proxy":
		hdrLines, err := renderHeaders(r.Headers)
		if err != nil {
			return nil, err
		}
		lines = append(lines, hdrLines...)
		lines = append(lines, fmt.Sprintf("\t\treverse_proxy 127.0.0.1:%d", *r.Port))
	case "static":
		quotedRoot, err := CaddyQuote(r.Root)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fmt.Sprintf("\t\troot * %s", quotedRoot))
		hdrLines, err := renderHeaders(r.Headers)
		if err != nil {
			return nil, err
		}
		lines = append(lines, hdrLines...)
		lines = append(lines, "\t\tfile_server")
	case "redirect":
		quotedTo, err := CaddyQuote(r.To)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fmt.Sprintf("\t\tredir %s permanent", quotedTo))
	default:
		return nil, fmt.Errorf("unsupported route type: %s", r.Type)
	}

	lines = append(lines, "\t}", "")
	return lines, nil
}

func ValidateGeneratedCaddy(caddyfileContent string, routesContent string) error {
	caddyfilePath := CaddyfilePath()
	dir := filepath.Dir(caddyfilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	tmpDir, err := os.MkdirTemp(dir, ".simple-vps-validate.")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	if err := os.Mkdir(filepath.Join(tmpDir, "simple-vps"), 0755); err != nil {
		return err
	}
	if err := os.Mkdir(filepath.Join(tmpDir, "conf.d"), 0755); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(tmpDir, "Caddyfile"), []byte(caddyfileContent), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "simple-vps", "routes.caddy"), []byte(routesContent), 0644); err != nil {
		return err
	}

	caddyBin := utils.CaddyBin()
	_, err = utils.RunChecked(caddyBin, []string{"validate", "--config", filepath.Join(tmpDir, "Caddyfile"), "--adapter", "caddyfile"}, "")
	return err
}

func ApplyCaddyfile(s *store.RoutesFile, force bool) (bool, error) {
	caddyfileContent := RenderCaddyfile()
	routesContent, err := RenderRoutesCaddyfile(s)
	if err != nil {
		return false, err
	}

	caddyfilePath := CaddyfilePath()
	routesCaddyfilePath := RoutesCaddyfilePath()
	if err := os.MkdirAll(filepath.Dir(caddyfilePath), 0755); err != nil {
		return false, err
	}
	if err := os.MkdirAll(ManagedCaddyDir(), 0755); err != nil {
		return false, err
	}
	if err := os.MkdirAll(UserCaddyDir(), 0755); err != nil {
		return false, err
	}

	caddyfileChanged := true
	if data, err := os.ReadFile(caddyfilePath); err == nil {
		caddyfileChanged = string(data) != caddyfileContent
	}

	routesChanged := true
	if data, err := os.ReadFile(routesCaddyfilePath); err == nil {
		routesChanged = string(data) != routesContent
	}

	if !caddyfileChanged && !routesChanged {
		return false, nil
	}

	if err := ValidateGeneratedCaddy(caddyfileContent, routesContent); err != nil {
		return false, err
	}

	if caddyfileChanged {
		if err := EnsureCanReplaceManagedFile(caddyfilePath, force, true); err != nil {
			return false, err
		}
	}
	if routesChanged {
		if err := EnsureCanReplaceManagedFile(routesCaddyfilePath, force, false); err != nil {
			return false, err
		}
	}

	// Backup modified files
	var backups []struct{ path, backup string }
	rollback := func() {
		// Revert in reverse order
		for i := len(backups) - 1; i >= 0; i-- {
			entry := backups[i]
			if entry.backup == "" {
				_ = os.Remove(entry.path)
			} else {
				_ = copyFile(entry.backup, entry.path)
			}
		}
		// Try reloading caddy to restore previous active config
		_ = reloadCaddy()
	}

	if caddyfileChanged {
		backup, err := utils.BackupFile(caddyfilePath)
		if err != nil {
			return false, err
		}
		backups = append(backups, struct{ path, backup string }{caddyfilePath, backup})
		if err := store.AtomicWrite(caddyfilePath, []byte(caddyfileContent), 0644); err != nil {
			rollback()
			return false, err
		}
	}

	if routesChanged {
		backup, err := utils.BackupFile(routesCaddyfilePath)
		if err != nil {
			return false, err
		}
		backups = append(backups, struct{ path, backup string }{routesCaddyfilePath, backup})
		if err := store.AtomicWrite(routesCaddyfilePath, []byte(routesContent), 0644); err != nil {
			rollback()
			return false, err
		}
	}

	// Validate final active files
	if _, err := utils.RunChecked(utils.CaddyBin(), []string{"validate", "--config", caddyfilePath, "--adapter", "caddyfile"}, ""); err != nil {
		rollback()
		return false, err
	}

	if err := reloadCaddy(); err != nil {
		rollback()
		return false, err
	}

	return true, nil
}

func copyFile(src string, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return store.AtomicWrite(dst, data, 0644)
}

func reloadCaddy() error {
	_, err := utils.RunChecked(utils.SystemctlBin(), []string{"reload", "caddy"}, "")
	return err
}
